import { useUserProfile } from './useUserProfile';
import { useMemo } from 'react';

const translations = {
  de: {
    // Dashboard & Navigation
    dashboardTitle: 'Webnest Dashboard',
    hello: 'Hallo',
    settings: 'Einstellungen',
    logout: 'Abmelden',
    createWithTemplate: 'Mit Template erstellen',
    createBlank: 'Leere Website erstellen',
    joinDevSession: 'Entwicklungssession beitreten',
    noWebsites: 'Noch keine Websites',
    createFirst: 'Erstelle deine erste Website mit unseren Templates oder starte mit einer leeren Seite!',
    
    // Loading states
    loading: 'Lädt...',
    loadingProfile: 'Lade Profil...',
    loadingWebsites: 'Lade Websites...',
    
    // User Settings
    userSettings: 'Benutzereinstellungen',
    tokenStatus: 'Token Status',
    availableTokens: 'Verfügbare Tokens',
    newWebsite: 'Neue Website: 3 Tokens',
    customPath: 'Custom Path: 8 Tokens',
    publishFree: 'Veröffentlichen: Kostenlos',
    deleteRefund: 'Löschen: Zeitbasierte Rückerstattung',
    collaborationRefund: 'Kollaboration: Zeitbasierte Rückerstattung',
    profile: 'Profil',
    email: 'E-Mail',
    name: 'Name',
    language: 'Sprache',
    german: 'Deutsch',
    english: 'English',
    appearance: 'Darstellung',
    darkMode: 'Dark Mode',
    
    // Toast messages
    languageChanged: 'Sprache geändert',
    settingsSaved: 'Einstellungen wurden gespeichert',
    error: 'Fehler',
    languageChangeError: 'Sprache konnte nicht geändert werden',
    darkModeChanged: 'Dark Mode geändert',
    darkModeError: 'Dark Mode konnte nicht geändert werden',
    loggedOut: 'Abgemeldet',
    seeYouLater: 'Bis zum nächsten Mal!',
    logoutError: 'Abmeldung fehlgeschlagen',
    deleted: 'Gelöscht',
    websiteDeleted: 'Website wurde erfolgreich gelöscht und Tokens erstattet',
    deleteError: 'Website konnte nicht gelöscht werden',
    notEnoughTokens: 'Nicht genügend Tokens',
    needTokensForWebsite: 'Du benötigst 2 Tokens um eine neue Website zu erstellen',
    projectCreateError: 'Projekt konnte nicht erstellt werden',
    blankWebsiteError: 'Leere Website konnte nicht erstellt werden',
    websiteNotFound: 'Website nicht gefunden',
    websiteNotFoundDesc: 'Die angeforderte Website existiert nicht',
    websiteLoadError: 'Website konnte nicht geladen werden',
    sessionWebsiteError: 'Website der Session konnte nicht gefunden werden',
    sessionNotFound: 'Session nicht gefunden',
    sessionNotFoundDesc: 'Die Session existiert nicht mehr oder ist beendet',
    sessionLoadError: 'Session konnte nicht geladen werden',
    saved: 'Gespeichert!',
    websiteSaved: 'Website wurde erfolgreich gespeichert',
    saveError: 'Website konnte nicht gespeichert werden',
    websiteUpdated: 'Website wurde erfolgreich aktualisiert',
    publishError: 'Website konnte nicht veröffentlicht werden',
    pathAlreadyTaken: 'Pfad bereits vergeben',
    pathAlreadyTakenDesc: 'Dieser Custom Path ist bereits in Verwendung',
    codeUpdated: 'Code Updated',
    codeUpdatedDesc: 'JavaScript code has been updated',
    warning: 'Warnung',
    
    // Login/Auth
    webnest: 'Webnest',
    createAccount: 'Erstelle dein kostenloses Konto',
    signInAccount: 'Melde dich in deinem Konto an',
    emailAddress: 'E-Mail-Adresse',
    password: 'Passwort',
    register: 'Registrieren',
    signIn: 'Anmelden',
    or: 'oder',
    signInWithGoogle: 'Mit Google anmelden',
    alreadyHaveAccount: 'Bereits ein Konto? Hier anmelden',
    noAccountYet: 'Noch kein Konto? Hier registrieren',
    accountCreated: 'Konto erstellt!',
    welcomeToWebnest: 'Willkommen bei Webnest!',
    signedIn: 'Angemeldet!',
    niceToSeeYou: 'Schön, dich wiederzusehen!',
    authError: 'Ein Fehler ist aufgetreten',
    googleSignInError: 'Google-Anmeldung fehlgeschlagen',
    
    // Template Selector
    selectTemplate: 'Template auswählen',
    templateSubtitle: 'Starte mit einem professionellen Design oder einer leeren Seite',
    blankWebsite: 'Leere Website',
    blankWebsiteDesc: 'Starte komplett von vorne',
    blankWebsitePreview: 'Eine leere weiße Seite zum freien Gestalten',
    landingPage: 'Landing Page',
    landingPageDesc: 'Perfekt für Produktvorstellungen und Marketing',
    landingPagePreview: 'Hero-Section mit Call-to-Action, Produktbild und modernem Design',
    businessWebsite: 'Business Website',
    businessWebsiteDesc: 'Professionelle Unternehmenswebsite',
    businessWebsitePreview: 'Klassisches Business-Layout mit Services und Kontaktmöglichkeiten',
    portfolio: 'Portfolio',
    portfolioDesc: 'Zeige deine Arbeiten und Projekte',
    portfolioPreview: 'Kreatives Portfolio-Design für Designer und Entwickler mit Projektbeispielen',
    onlineShop: 'Online Shop',
    onlineShopDesc: 'E-Commerce Website für Produkte',
    onlineShopPreview: 'Shop-Layout mit Produktgalerie, Preisen und Newsletter-Anmeldung',
    createNewProject: 'Neues Projekt erstellen',
    projectNameDesc: 'Gib deinem Projekt einen Namen um mit dem {template} zu starten.',
    projectNamePlaceholder: 'z.B. Meine Awesome Website',
    cancel: 'Abbrechen',
    createProject: 'Projekt erstellen',
    
    // Website Builder Actions
    websitePreview: 'Website Vorschau',
    save: 'Speichern',
    publish: 'Veröffentlichen',
    back: 'Zurück',
    edit: 'Bearbeiten',
    view: 'Ansehen',
    delete: 'Löschen',
    refresh: 'Aktualisieren',
    classicPublish: 'Classic Publish (Gratis)',
    customPublish: 'Custom Path (5 Tokens)',
    chooseCustomPath: 'Wähle deinen eigenen Projektnamen (z.B. "meine-awesome-website")',
    customPathPlaceholder: 'meine-awesome-website',
    publishWebsite: 'Website veröffentlichen',
    rename: 'Umbenennen',
    enterNewWebsiteName: 'Neuen Namen für die Website eingeben:',
    
    // Website Status
    published: 'Veröffentlicht',
    draft: 'Entwurf',
    createdOn: 'Erstellt am',
    
    // Collaboration
    collaboration: 'Kollaboration',
    startSession: 'Session starten',
    joinSession: 'Session beitreten',
    sessionPin: 'Session PIN',
    enterPin: '6-stellige PIN eingeben',
    joining: 'Beitreten...',
    sessionJoined: 'Session beigetreten!',
    sessionJoinedDesc: 'Sie sind der Session {pin} beigetreten',
    sessionJoinError: 'Session konnte nicht beigetreten werden',
    sessionCreateError: 'Session konnte nicht erstellt werden',
    pinCopied: 'PIN kopiert!',
    pinCopiedDesc: 'PIN wurde in die Zwischenablage kopiert',
    maxParticipants: 'Maximale Teilnehmer',
    participants2: '2 Teilnehmer (20 Tokens)',
    participants3: '3 Teilnehmer (30 Tokens)',
    participants4: '4 Teilnehmer (40 Tokens)',
    participants5: '5 Teilnehmer (50 Tokens)',
    tokenCost: 'Token-Kosten:',
    tokens: 'Tokens',
    baseTokens: 'Tokens Basis',
    additionalTokens: 'Tokens für zusätzliche Slots',
    notEnoughTokensAvailable: 'Nicht genügend Tokens verfügbar',
    creatingSession: 'Session wird erstellt...',
    collaborativeEditing: 'Kollaborative Bearbeitung',
    participants: 'Teilnehmer',
    leaveSession: 'Session verlassen',
    sessionEnded: 'Session beendet',
    sessionEndedDesc: 'Die Kollaborationssession wurde beendet',
    connectionError: 'Verbindungsfehler',
    dbConnectionFailed: 'Datenbankverbindung fehlgeschlagen',
    newParticipant: 'Neuer Teilnehmer',
    participantJoined: '{name} ist der Session beigetreten',
    participantLeft: 'Teilnehmer verlassen',
    participantLeftDesc: 'Ein Teilnehmer hat die Session verlassen',
    connectionLost: 'Verbindung verloren',
    connectionLostDesc: 'Firestore Verbindung wurde unterbrochen. Versuche Wiederverbindung...',
    connectionRestored: 'Verbindung hergestellt',
    liveEditingActive: 'Live Bearbeitung aktiv!',
    firestoreError: 'Firestore Fehler',
    
    // Element Properties
    textContent: 'Text Inhalt',
    textColor: 'Textfarbe',
    fontSize: 'Schriftgröße (px)',
    buttonText: 'Button Text',
    backgroundColor: 'Hintergrundfarbe',
    customJavaScript: 'Custom JavaScript',
    elementLinkText: 'Link Text',
    elementUrl: 'URL',
    urlPlaceholder: 'https://example.com',
    youtubeUrl: 'YouTube URL',
    labelText: 'Label Text',
    navigation: 'Navigation',
    elementButton: 'Button',
    imageUrl: 'Bild URL',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    altText: 'Alt Text',
    inputId: 'Input ID',
    inputIdPlaceholder: 'myInput',
    inputType: 'Input Type',
    placeholderText: 'Platzhalter Text',
    elementProperties: '{type} Eigenschaften',
    deleteElement: 'Element löschen',
    
    // 404 Page
    pageNotFound: 'Oops! Page not found',
    returnToHome: 'Return to Home',
    
    // Website Viewer
    websiteNotExists: 'Die Website {id} existiert nicht.',
    websiteWithAutoUrl: 'Website mit automatischer URL',
    websiteWithCustomUrl: 'Eigene URL wie "meine-website"',
    
    // Element Labels
    elementText: 'Text',
    elementButtonLabel: 'Button',
    elementImage: 'Bild',
    elementInput: 'Eingabefeld',
    elementLinkTextLabel: 'Link Text',
    elementYoutube: 'YouTube',
    elementDarkToggle: 'Dark Toggle',
    elementTopbar: 'Topbar',
    
    // Code Blocks
    redirectToUrl: 'Redirect To URL',
    redirectDesc: 'Navigate to a different webpage',
    showAlert: 'Show Alert',
    alertDesc: 'Display a popup message',
    logToConsole: 'Log to Console',
    consoleDesc: 'Print message to browser console',
    readInputValue: 'Read Input Value',
    readInputDesc: 'Get value from an input field',
    noBlocksYet: 'No blocks yet',
    
    // Input Types
    inputTextType: 'Text',
    inputEmailType: 'Email',
    inputPasswordType: 'Password',
    inputNumberType: 'Number',
    inputPhoneType: 'Phone',
    inputUrlType: 'URL',
  },
  en: {
    // Dashboard & Navigation
    dashboardTitle: 'Webnest Dashboard',
    hello: 'Hello',
    settings: 'Settings',
    logout: 'Logout',
    createWithTemplate: 'Create with template',
    createBlank: 'Create blank website',
    joinDevSession: 'Join development session',
    noWebsites: 'No websites yet',
    createFirst: 'Create your first website with our templates or start with a blank page!',
    
    // Loading states
    loading: 'Loading...',
    loadingProfile: 'Loading profile...',
    loadingWebsites: 'Loading websites...',
    
    // User Settings
    userSettings: 'User Settings',
    tokenStatus: 'Token Status',
    availableTokens: 'Available Tokens',
    newWebsite: 'New Website: 3 Tokens',
    customPath: 'Custom Path: 8 Tokens',
    publishFree: 'Publish: Free',
    deleteRefund: 'Delete: Time-based refund',
    collaborationRefund: 'Collaboration: Time-based refund',
    profile: 'Profile',
    email: 'Email',
    name: 'Name',
    language: 'Language',
    german: 'German',
    english: 'English',
    appearance: 'Appearance',
    darkMode: 'Dark Mode',
    
    // Toast messages
    languageChanged: 'Language changed',
    settingsSaved: 'Settings saved',
    error: 'Error',
    languageChangeError: 'Language could not be changed',
    darkModeChanged: 'Dark mode changed',
    darkModeError: 'Dark mode could not be changed',
    loggedOut: 'Logged out',
    seeYouLater: 'See you later!',
    logoutError: 'Logout failed',
    deleted: 'Deleted',
    websiteDeleted: 'Website successfully deleted and tokens refunded',
    deleteError: 'Website could not be deleted',
    notEnoughTokens: 'Not enough tokens',
    needTokensForWebsite: 'You need 2 tokens to create a new website',
    projectCreateError: 'Project could not be created',
    blankWebsiteError: 'Blank website could not be created',
    websiteNotFound: 'Website not found',
    websiteNotFoundDesc: 'The requested website does not exist',
    websiteLoadError: 'Website could not be loaded',
    sessionWebsiteError: 'Session website could not be found',
    sessionNotFound: 'Session not found',
    sessionNotFoundDesc: 'The session no longer exists or has ended',
    sessionLoadError: 'Session could not be loaded',
    saved: 'Saved!',
    websiteSaved: 'Website successfully saved',
    saveError: 'Website could not be saved',
    websiteUpdated: 'Website successfully updated',
    publishError: 'Website could not be published',
    pathAlreadyTaken: 'Path already taken',
    pathAlreadyTakenDesc: 'This custom path is already in use',
    codeUpdated: 'Code Updated',
    codeUpdatedDesc: 'JavaScript code has been updated',
    warning: 'Warning',
    
    // Login/Auth
    webnest: 'Webnest',
    createAccount: 'Create your free account',
    signInAccount: 'Sign in to your account',
    emailAddress: 'Email address',
    password: 'Password',
    register: 'Register',
    signIn: 'Sign In',
    or: 'or',
    signInWithGoogle: 'Sign in with Google',
    alreadyHaveAccount: 'Already have an account? Sign in here',
    noAccountYet: 'No account yet? Register here',
    accountCreated: 'Account created!',
    welcomeToWebnest: 'Welcome to Webnest!',
    signedIn: 'Signed in!',
    niceToSeeYou: 'Nice to see you again!',
    authError: 'An error occurred',
    googleSignInError: 'Google sign-in failed',
    
    // Template Selector
    selectTemplate: 'Select Template',
    templateSubtitle: 'Start with a professional design or a blank page',
    blankWebsite: 'Blank Website',
    blankWebsiteDesc: 'Start completely from scratch',
    blankWebsitePreview: 'A blank white page for free design',
    landingPage: 'Landing Page',
    landingPageDesc: 'Perfect for product presentations and marketing',
    landingPagePreview: 'Hero section with call-to-action, product image and modern design',
    businessWebsite: 'Business Website',
    businessWebsiteDesc: 'Professional business website',
    businessWebsitePreview: 'Classic business layout with services and contact options',
    portfolio: 'Portfolio',
    portfolioDesc: 'Show your work and projects',
    portfolioPreview: 'Creative portfolio design for designers and developers with project examples',
    onlineShop: 'Online Shop',
    onlineShopDesc: 'E-commerce website for products',
    onlineShopPreview: 'Shop layout with product gallery, prices and newsletter signup',
    createNewProject: 'Create New Project',
    projectNameDesc: 'Give your project a name to start with {template}.',
    projectNamePlaceholder: 'e.g. My Awesome Website',
    cancel: 'Cancel',
    createProject: 'Create Project',
    
    // Website Builder Actions
    websitePreview: 'Website Preview',
    save: 'Save',
    publish: 'Publish',
    back: 'Back',
    edit: 'Edit',
    view: 'View',
    delete: 'Delete',
    refresh: 'Refresh',
    classicPublish: 'Classic Publish (Free)',
    customPublish: 'Custom Path (5 Tokens)',
    chooseCustomPath: 'Choose your own project name (e.g. "my-awesome-website")',
    customPathPlaceholder: 'my-awesome-website',
    publishWebsite: 'Publish Website',
    rename: 'Rename',
    enterNewWebsiteName: 'Enter a new name for the website:',
    
    // Element Properties
    textContent: 'Text Content',
    textColor: 'Text Color',
    fontSize: 'Font Size (px)',
    buttonText: 'Button Text',
    backgroundColor: 'Background Color',
    customJavaScript: 'Custom JavaScript',
    elementLinkText: 'Link Text',
    elementUrl: 'URL',
    urlPlaceholder: 'https://example.com',
    youtubeUrl: 'YouTube URL',
    labelText: 'Label Text',
    navigation: 'Navigation',
    elementButton: 'Button',
    imageUrl: 'Image URL',
    imageUrlPlaceholder: 'https://example.com/image.jpg',
    altText: 'Alt Text',
    inputId: 'Input ID',
    inputIdPlaceholder: 'myInput',
    inputType: 'Input Type',
    placeholderText: 'Placeholder Text',
    elementProperties: '{type} Properties',
    deleteElement: 'Delete Element',
    
    // Collaboration
    collaboration: 'Collaboration',
    startSession: 'Start Session',
    joinSession: 'Join Session',
    sessionPin: 'Session PIN',
    enterPin: 'Enter 6-digit PIN',
    joining: 'Joining...',
    sessionJoined: 'Session joined!',
    sessionJoinedDesc: 'You have joined session {pin}',
    sessionJoinError: 'Could not join session',
    sessionCreateError: 'Could not create session',
    pinCopied: 'PIN copied!',
    pinCopiedDesc: 'PIN has been copied to clipboard',
    maxParticipants: 'Maximum Participants',
    participants2: '2 Participants (20 Tokens)',
    participants3: '3 Participants (30 Tokens)',
    participants4: '4 Participants (40 Tokens)',
    participants5: '5 Participants (50 Tokens)',
    tokenCost: 'Token Cost:',
    tokens: 'Tokens',
    baseTokens: 'Base Tokens',
    additionalTokens: 'Tokens for additional slots',
    notEnoughTokensAvailable: 'Not enough tokens available',
    creatingSession: 'Creating session...',
    collaborativeEditing: 'Collaborative Editing',
    participants: 'Participants',
    leaveSession: 'Leave Session',
    sessionEnded: 'Session ended',
    sessionEndedDesc: 'The collaboration session has ended',
    connectionError: 'Connection Error',
    dbConnectionFailed: 'Database connection failed',
    newParticipant: 'New Participant',
    participantJoined: '{name} has joined the session',
    participantLeft: 'Participant Left',
    participantLeftDesc: 'A participant has left the session',
    connectionLost: 'Connection Lost',
    connectionLostDesc: 'Firestore connection was interrupted. Attempting to reconnect...',
    connectionRestored: 'Connection Restored',
    liveEditingActive: 'Live editing active!',
    firestoreError: 'Firestore Error',
    
    // 404 Page
    pageNotFound: 'Oops! Page not found',
    returnToHome: 'Return to Home',
    
    // Website Viewer
    websiteNotExists: 'The website {id} does not exist.',
    websiteWithAutoUrl: 'Website with automatic URL',
    websiteWithCustomUrl: 'Custom URL like "my-website"',
    
    // Element Labels
    elementText: 'Text',
    elementButtonLabel: 'Button',
    elementImage: 'Image',
    elementInput: 'Input Field',
    elementLinkTextLabel: 'Link Text',
    elementYoutube: 'YouTube',
    elementDarkToggle: 'Dark Toggle',
    elementTopbar: 'Topbar',
    
    // Code Blocks
    redirectToUrl: 'Redirect To URL',
    redirectDesc: 'Navigate to a different webpage',
    showAlert: 'Show Alert',
    alertDesc: 'Display a popup message',
    logToConsole: 'Log to Console',
    consoleDesc: 'Print message to browser console',
    readInputValue: 'Read Input Value',
    readInputDesc: 'Get value from an input field',
    noBlocksYet: 'No blocks yet',
    
    // Input Types
    inputTextType: 'Text',
    inputEmailType: 'Email',
    inputPasswordType: 'Password',
    inputNumberType: 'Number',
    inputPhoneType: 'Phone',
    inputUrlType: 'URL',
  }
};

export function useLanguage() {
  const { profile } = useUserProfile();
  const lang = profile?.language || 'de';
  const t = useMemo(() => {
    return (key: keyof typeof translations['de'], params?: Record<string, string>) => {
      let translation = translations[lang][key] || translations['de'][key] || key;
      
      // Replace parameters in translation
      if (params) {
        Object.entries(params).forEach(([param, value]) => {
          translation = translation.replace(`{${param}}`, value);
        });
      }
      
      return translation;
    };
  }, [lang]);
  return { lang, t };
} 